# Generated by Django 4.0.3 on 2022-12-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
